apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: johnojss/mern-backend
          ports:
            - containerPort: 4000
              name: nodejs-port
  selector:
    matchLabels:
      app: server
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: production
spec:
  ports:
    - port: 4000
      protocol: TCP
  selector:
    app: server
#  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "backend-prod"
spec:
  rules:
    - host: be.jokoss.site
      http:
        paths:
          #- path: /belajar
          - backend:
              serviceName: backend-service
              servicePort: 4000
  tls:
    - hosts:
        - be.jokoss.site
      secretName: backend-ssl

---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: backend-prod
  namespace: production
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: johno.smakaduta@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: backend-prod
    # Enable the HTTP-01 challenge provider
    solvers:
      - selector: {}
        http01:
          ingress:
            class: nginx
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-prod-hpa
  namespace: production
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 90
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 90
