apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: production
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-port
  selector:
    app: client
#  type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: fe.jokoss.site
    http:
      paths:
      #- path: /belajar
      - backend:
          serviceName: frontend-service
          servicePort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: johnojss/mern-frontend
          ports:
            - containerPort: 3000
              name: http-port
  selector:
    matchLabels:
      app: client
