apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: production
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-port
  selector:
    app: client
#  type: LoadBalancer

---

apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
 name: letsencrypt-frontend-prod
 namespace: cert-manager
spec:
 acme:
   # The ACME server URL
   server: https://acme-v02.api.letsencrypt.org/directory
   # Email address used for ACME registration
   email: johno.smakaduta@gmail.com
   # Name of a secret used to store the ACME account private key
   privateKeySecretRef:
     name: letsencrypt-frontend-prod
   # Enable the HTTP-01 challenge provider
   solvers:
   - http01:
       ingress:
         class:  nginx

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: production
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-frontend-prod"
spec:
  rules:
  - host: fe.jokoss.site
    http:
      paths:
      #- path: /belajar
      - backend:
          serviceName: frontend-service
          servicePort: 80

  tls:
    - hosts:
        - fe.jokoss.site
      secretName: fe-prod-tls
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: johnojss/mern-frontend
          ports:
            - containerPort: 3000
              name: http-port
  selector:
    matchLabels:
      app: client
