apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  namespace: production
  labels:
    app: mongodb
spec:
  containers:
    - name: mongodb
      image: mongo:4.0.4
      ports:
        - containerPort: 27017
          name: mongodb-port

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: production
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    app: mongodb
  type: LoadBalancer
