apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongodb
  namespace: production
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: production
  labels:
    app: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: '/data/db'
              name: mongo-storage
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: pvc-mongodb
  selector:
    matchLabels:
      app: mongodb
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: production
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    app: mongodb
  type: LoadBalancer
